#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor eDP1 -d 1 2 3 4 5
# bspc monitor HDMI-1 -d VI VII VIII IX X
picom &
wal -i ~/Sources/wallpapers/ &
polybar bar -c ~/.config/polybar/config &
polybar bar_external -c ~/.config/polybar/config &
bash ~/Sources/Zathura-Pywal/install.sh
pywal-discord

bspc config border_width         2
bspc config window_gap           5

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true

bspc rule -a Zathura state=tiled
betterlockscreen -u ~/Sources/wallpapers/
